### ISSUE TITLE
Building for MacOSX with M1 chip (arm) fails

### ISSUE THREAD

**Issue by jaybi** [isotopec-org/IsotopeC#1]
Hello, I am facing an issue during the make process.

### Describe the issue
Build fails at make step

#### If so, please list the steps to reproduce below:
1. Grab my Mac 
2. Xcode previously installed
3. Install all dependencies with Brew (option --without-single not recognized)
4. Git clone...
5. Autogen: ok 
6. Configure: ok
7. Make: error

### Expected behaviour
The binary is compiled

### Actual behaviour
Making all in src
  CXX      bitcoind-bitcoind.o
In file included from bitcoind.cpp:14:
In file included from ./interfaces/chain.h:10:
In file included from ./util/settings.h:8:
./fs.h:14:10: fatal error: 'boost/filesystem.hpp' file not found
#include <boost/filesystem.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [bitcoind-bitcoind.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

### What version of bitcoin-core are you using?
https://github.com/isotopec-org/IsotopeC/commit/adc231b526723ee17f185241e581ed088126d1ae

### Machine specs:
- OS: MacOS 11.2.1 BigSur 
- CPU: M1
- RAM: 16
- Disk size: 512
- Disk Type (HD/SDD): SSD

**Comment by isotopec-org** [comment]
The Apple M1 is an ARM-based system on a chip (SoC) and the architecture and instruction sets [ARMv8.4-A] is vastly different than Intel based x86 architectures. Its power-use optimizations are not possible with the current build of IsotopeC due to the M1 design and is forthcoming for just the wallet.
IsotopeC (wallet) would require a build based exclusively for the M1 chipset and will not include a built in CPU Miner due to the reduced power of the M1 (5 watts).
Although, mining is possible on the M1, but the reduced power consumption of the M1 would yield an extremely small hashrate that will not fair well and competing with other miners as a solo miner would be a waste of time. Furthermore, Yespower is memory dependent and is not ARM friendly.
At this time there are no plans to support the M1, or any ARM based processor.
